### ISSUE TITLE
Replace Teamcity/TravisCI/CircleCI with Jenkins

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/testing#78]
_From @VictorBjelkholm on January 29, 2017 15:33_

# Acceptance Criteria

- [ ] go-ipfs, js-ipfs-api and js-ipfs uses Jenkins instead of Teamcity/TraviCI and CircleCI

# Tasks
- [ ] Way of storing secrets for
    - [ ] Coverage uploading [CircleCI]
- [ ] Disable the services in Github
- [ ] Remove configuration files for services

# Dependencies

Depends on #1  
Depends on #2  
Depends on #3  
Depends on #4 
Depends on #5 
Depends on #7

_Copied from original issue: ipfs/jenkins#6_

**Comment by VictorBjelkholm** [comment]
Status update:

- js-ipfs-api is using jenkins already!
- js-ipfs has a PR pending, just a couple of windows tests are missing: https://github.com/ipfs/js-ipfs/pull/1103
- go-ipfs has a PR pending with a couple of things missing: https://github.com/ipfs/go-ipfs/pull/4430

**Comment by VictorBjelkholm** [comment]
This has been split out in many issues by now.
