### ISSUE TITLE
Allow to stop builds for users allowed to start them

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/testing#80]
_From @Kubuxu on February 4, 2017 16:58_

# Acceptance Criteria
- [ ] As a owner of a repository that runs a job in jenkins, I should be allowed to cancel those jobs
- [ ] As a contributer to a repository that runs a job in jenkins, I should be allowed to cancel those jobs
# Tasks
- [ ] Make sure Github Authentication is setup correctly for passing AC
# Notes
Original post from @Kubuxu 
> Or we can have separate group.

_Copied from original issue: ipfs/jenkins#30_
